<img style="float:right" width="25%" src="EscudoColorTc.jpg">
<h1 style="display: inline-block; padding: 4mm; padding-left= 2em; background-color: navy; line-height: 1.3em; color: white; border-radius: 10px">

    Práctica 6: Recomendación basada en memoria
</h1>

## Gestión de la Información. Curso 2025-2026

## Alumnos:
* Belén Rodríguez Cánovas
* Fernando Arroyo Redondo
___

# 1. Instalación de librerías necesarias

In [1]:
# Se importa la librería numpy que se va a usar para los vectores que se van a usar
import numpy as np
# Se importa la librería pandas para importar los ficheros csv que se van a necesitar
import pandas as pd
# Se importa la librería pyplot para la creación de gráficos
import matplotlib.pyplot as plt
# Se importa las librerías de sklearn que permiten hacer imágenes de clusters
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 2. Importación de datos a un Dataframe

In [2]:
# Diccionario de datos de usuarios y valoraciones
# Se almacena usando un Dataframe de pandas transformado luego en diccionario
# El fichero se ha creado usando los ficheros proporcionados en el enlace del problema
# Posteriormente se ha unificado en un fichero dataset.xlxs con los campos siguientes:
# userId, movieId, rating

# 1 Carga en el dataframe
df = pd.read_excel('dataset.xlsx')

In [3]:
# Control de carga
print (df[:4])
print(".....")
print(df[-4:])

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
.....
        userId  movieId  rating
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0


# 3. Transformación del dataframe en diccionario

In [4]:
# Se agrupa por userId y luego transforma cada grupo en un dicionario donde la clave es movieId 
# y los valores Title y rating
data = {
    user_id:dict(zip(user_data['movieId'],user_data['rating']))
    for user_id, user_data in df.groupby('userId')
}
    


In [5]:
# Valoracián de una película en particular usuario 1
data[1][1] # Valoración usuario A película 'Toy Story'

4.0

In [6]:
print(data[1])

{1: 4.0, 3: 4.0, 6: 4.0, 47: 5.0, 50: 5.0, 70: 3.0, 101: 5.0, 110: 4.0, 151: 5.0, 157: 5.0, 163: 5.0, 216: 5.0, 223: 3.0, 231: 5.0, 235: 4.0, 260: 5.0, 296: 3.0, 316: 3.0, 333: 5.0, 349: 4.0, 356: 4.0, 362: 5.0, 367: 4.0, 423: 3.0, 441: 4.0, 457: 5.0, 480: 4.0, 500: 3.0, 527: 5.0, 543: 4.0, 552: 4.0, 553: 5.0, 590: 4.0, 592: 4.0, 593: 4.0, 596: 5.0, 608: 5.0, 648: 3.0, 661: 5.0, 673: 3.0, 733: 4.0, 736: 3.0, 780: 3.0, 804: 4.0, 919: 5.0, 923: 5.0, 940: 5.0, 943: 4.0, 954: 5.0, 1009: 3.0, 1023: 5.0, 1024: 5.0, 1025: 5.0, 1029: 5.0, 1030: 3.0, 1031: 5.0, 1032: 5.0, 1042: 4.0, 1049: 5.0, 1060: 4.0, 1073: 5.0, 1080: 5.0, 1089: 5.0, 1090: 4.0, 1092: 5.0, 1097: 5.0, 1127: 4.0, 1136: 5.0, 1196: 5.0, 1197: 5.0, 1198: 5.0, 1206: 5.0, 1208: 4.0, 1210: 5.0, 1213: 5.0, 1214: 4.0, 1219: 2.0, 1220: 5.0, 1222: 5.0, 1224: 5.0, 1226: 5.0, 1240: 5.0, 1256: 5.0, 1258: 3.0, 1265: 4.0, 1270: 5.0, 1275: 5.0, 1278: 5.0, 1282: 5.0, 1291: 5.0, 1298: 5.0, 1348: 4.0, 1377: 3.0, 1396: 3.0, 1408: 3.0, 1445: 3.0, 1

# 4. Función para pasar del diccionario a las matrices Y(ratings), R(películas vistas)

In [7]:
def dic_ratings2arrays(dic):
    # Usuarios
    k1=np.unique(list(dic.keys())) #array usuarios
    
    # Películas
    k2=[]
    for i in k1:
        k2=k2 + list(dic[i].keys())

    k2=np.unique(k2) # array de películas

    # Valoraciones
    Y= np.zeros ((len(k1),len(k2))) #array de ratins creado  a cero
    # Relleno de valores de Y, recorriendo los dos vectores de usuarios y películas
    for i in k1:
        for j in k2:
            if j in dic[i].keys():
                Y[k1.tolist().index(i),k2.tolist().index(j)]= dic[i][j]
    return (Y,(Y>0)*1,k1,k2) #La matriz R es (Y>0)*1

# 5. Añadir dos usuarios

In [8]:
data[611] = {1:4.7,552:4.3, 1023:4.5, 1270:4.0,2115:4.0, 30793:4.5}
data[612] ={1:3.5,552:3.2, 1090:4.5, 1092:4.6, 1208:4.0,2115:4.0, 20571:4.8, 99114:4.5, 912:4.0, 1079:3.9}

In [9]:
# Comprobar datos añadidos
print(data[611])
print(data[612])

{1: 4.7, 552: 4.3, 1023: 4.5, 1270: 4.0, 2115: 4.0, 30793: 4.5}
{1: 3.5, 552: 3.2, 1090: 4.5, 1092: 4.6, 1208: 4.0, 2115: 4.0, 20571: 4.8, 99114: 4.5, 912: 4.0, 1079: 3.9}


# 6. Creación de matrices Y y R

In [10]:
(Y,R,users,movies)=dic_ratings2arrays(data)

In [11]:
# Visualizacián de datos para ver algunos resultados

print ('Matiz de valoraciones Y\n',Y[0]) # primer usuario de la matriz
print ('Matriz R\n',R[0]) # primera película de la matriz
print ('Usuarios\n',users[:10]) # 10 primeros usurios del conjunto de datos
print ('Películas\n',movies[:10])  # 10 primeras películas del conjunto de datos

Matiz de valoraciones Y
 [4. 0. 4. ... 0. 0. 0.]
Matriz R
 [1 0 1 ... 0 0 0]
Usuarios
 [ 1  2  3  4  5  6  7  8  9 10]
Películas
 [ 1  2  3  4  5  6  7  8  9 10]


# 7. Función para calcular la correlación de Pearson

In [16]:
# Correlacióon de Pearson (coincidencia en el espacio de valoraciones)
def pearson_similarity(Y,R,a,b):
    # Funciona con vectores fila
    common_ratings = (R[a,:]>0)&(R[b,:]>0) # Coincidencia en el espacio de valoraciones
    if common_ratings.any():
        # el promedio es sobre todas las valoraciones
        # Se consigue la media donde la matriz R tenga valores estrictamente positivos, 
        #lo que da una media sin tener en cuenta los ceros ver ejemplo en siguiente casilla
        a_average = Y[a,R[a,:]>0].mean() 
        b_average = Y[b,R[b,:]>0].mean()
        pcorr = np.dot(Y[a,common_ratings] - a_average,Y[b,common_ratings] - b_average)/(
                np.sqrt(np.dot(Y[a,common_ratings] - a_average,Y[a,common_ratings] - a_average))*
                np.sqrt(np.dot(Y[b,common_ratings] - b_average,Y[b,common_ratings] - b_average)))
        if np.isnan(pcorr): # En el caso de que se presente una indeterminación
            return 0
        else:
            return pcorr
    else: # En el caso de no haber una coincidencia en el espacio de valoraciones
        return 0

In [17]:
Y[0,R[0,:]>0].mean() #Media de valoración del usuario A

np.float64(4.366379310344827)

In [20]:
# Cálculo de la similitud de dos usuarios usuario A y usuario C
for (u1,u2) in [(0,2)]:
    print('Similitud entre ',users[u1], 'y ',users[u2])
    print('Coeficiente de Pearson: %0.4f'% pearson_similarity(Y,R,u1,u2))

Similitud entre  1 y  3
Coeficiente de Pearson: 0.0112


In [ ]:
# Cálculo de la similitud de todos los usuarios, si fuera necesario calcularla, el tamaño actual es muy grande
for u1 in range (Y.shape[0]):
    for u2 in range (u1 +1,Y.shape[0]):
        print('Similitud entre ( ',users[u1], ', ',users[u2], '): %0.4f'% pearson_similarity(Y,R,u1,u2))

# 8. Cálculo de la matriz de similitud

In [21]:
#Cálculo de la matriz de similitud
def user_similarity_matrix(Y,R):
    matrix = np.zeros((Y.shape[0],Y.shape[0]))
    for u1 in range (Y.shape[0]):
        for u2 in range (u1,Y.shape[0]):
            matrix[u1,u2] = pearson_similarity(Y,R,u1,u2)
            if u1!=u2:
                matrix[u2,u1]=matrix[u1,u2]
    return matrix

# Mostrar la matriz. Si fuera necesario, el tamaño es muy grande
print ('Matriz de similitud\n',user_similarity_matrix(Y,R))

# 9. Encontrar usuarios que evaluaron Toys Story

In [22]:
item_i=1 # el item 1 corresponde a Toys Story
k=np.where(R[:,item_i]>0)[0]
print (k)

[  5   7  17  18  19  20  26  50  61  67  81  90  92  93 102 103 106 111
 116 121 124 134 139 143 148 152 159 168 176 185 201 216 218 220 221 225
 229 231 239 248 258 273 275 283 287 293 297 298 303 304 306 307 317 320
 321 322 329 346 352 356 358 372 379 380 394 410 413 424 425 431 433 435
 445 446 447 457 469 473 474 475 476 479 481 482 483 488 496 500 511 516
 522 524 526 533 558 560 562 565 569 572 585 589 591 593 598 599 601 603
 604 607]


In [24]:
# Calcular la similitud de los k usuarios al usuario 607
user_sim = user_similarity_matrix(Y,R)
user_u=607 # El primero que se ha añadido
k_sim = user_sim[user_u,k]


C:\Users\35266\AppData\Local\Temp\ipykernel_14056\608130604.py:11: RuntimeWarning: invalid value encountered in scalar divide
  pcorr = np.dot(Y[a,common_ratings] - a_average,Y[b,common_ratings] - b_average)/(


In [25]:
print(k_sim)

[ 0.07993695  0.429588    0.31235709  0.18185246  0.03290241  0.04368462
  0.03416152  0.15579616  0.19442769  0.23378651  0.25252548  0.40275772
  0.1083873   0.37438574  0.26444112 -0.10228318 -0.06843941  0.57959954
  0.19491648  0.25249373  0.24437929  0.36518226  0.03546867  0.29303247
  0.360361    0.09530468  0.21210598  0.03062277  0.12622966  0.12297515
  0.214953    0.22946815  0.26658303  0.10240328  0.40944085  0.26170587
  0.31112611  0.43677854  0.06689818  0.37402564  0.071169    0.25778486
 -0.03618249  0.1838261   0.20804792  0.4017754   0.24475777  0.11716617
 -0.00411616  0.15727141  0.47317894 -0.1711975  -0.05685212  0.07030684
  0.03112085  0.20937408  0.2805719  -0.04083901  0.41556055  0.22353447
  0.26309405  0.51256997  0.21759527  0.21918909  0.15143077  0.09258386
  0.32001662  0.3214758  -0.38703639  0.18018218  0.19824831  0.08840618
  0.3706297   0.17961572  0.11750851  0.02523896  0.00225337  0.31227789
  0.17426522 -0.05881751  0.30741874  0.2556414   0

In [27]:
# Unir índices de usuarios y similitudes: da una lista de tuplas
# primera posicián de la tupla con la similitud del usuario y de qué usuario se trata en segunda posisión
k_zip = list(zip(k_sim,k))
print ('Usuarios que vieron Toys Story\n', k_zip)

Usuarios que vieron Toys Story
 [(np.float64(0.07993694843744983), np.int64(5)), (np.float64(0.4295880013968585), np.int64(7)), (np.float64(0.31235708595170975), np.int64(17)), (np.float64(0.1818524568524517), np.int64(18)), (np.float64(0.032902411674092275), np.int64(19)), (np.float64(0.043684622150646106), np.int64(20)), (np.float64(0.03416152016234466), np.int64(26)), (np.float64(0.1557961638121222), np.int64(50)), (np.float64(0.1944276860091965), np.int64(61)), (np.float64(0.2337865105347111), np.int64(67)), (np.float64(0.2525254751455133), np.int64(81)), (np.float64(0.40275771979353114), np.int64(90)), (np.float64(0.10838730076078794), np.int64(92)), (np.float64(0.37438573530795477), np.int64(93)), (np.float64(0.26444111951468524), np.int64(102)), (np.float64(-0.10228318188595505), np.int64(103)), (np.float64(-0.06843940550393932), np.int64(106)), (np.float64(0.5795995449007063), np.int64(111)), (np.float64(0.19491648430901182), np.int64(116)), (np.float64(0.25249373029586486), np

In [28]:
# Si se quiere eliminar los índices de usuarios con similitud negativa que distorsionan el coeficiente
k_zip=[k_zip[i] for i in range (len(k_zip)) if k_zip[i][0]> 0]
print ('Usuarios con similitud positiva que vieron Toys Story\n',k_zip)

Usuarios con similitud positiva que vieron Toys Story
 [(np.float64(0.07993694843744983), np.int64(5)), (np.float64(0.4295880013968585), np.int64(7)), (np.float64(0.31235708595170975), np.int64(17)), (np.float64(0.1818524568524517), np.int64(18)), (np.float64(0.032902411674092275), np.int64(19)), (np.float64(0.043684622150646106), np.int64(20)), (np.float64(0.03416152016234466), np.int64(26)), (np.float64(0.1557961638121222), np.int64(50)), (np.float64(0.1944276860091965), np.int64(61)), (np.float64(0.2337865105347111), np.int64(67)), (np.float64(0.2525254751455133), np.int64(81)), (np.float64(0.40275771979353114), np.int64(90)), (np.float64(0.10838730076078794), np.int64(92)), (np.float64(0.37438573530795477), np.int64(93)), (np.float64(0.26444111951468524), np.int64(102)), (np.float64(0.5795995449007063), np.int64(111)), (np.float64(0.19491648430901182), np.int64(116)), (np.float64(0.25249373029586486), np.int64(121)), (np.float64(0.24437929495095723), np.int64(124)), (np.float64(0.3

In [29]:
# Media de las valoraciones del usuario 607 (sobre las películas que si haya visto)
user_u_average=Y[user_u,R[user_u,:]>0].mean()
print(user_u_average)

3.1341756919374246


In [30]:
# Suma de los valores absolutos de similitud de vecinos próximos al usuario 607
k_sim=[k_zip[i][0] for i in range(len(k_zip))]
print(k_sim)
k_sim_suma=np.abs(np.array(k_sim)).sum()
print (k_sim_suma)

[np.float64(0.07993694843744983), np.float64(0.4295880013968585), np.float64(0.31235708595170975), np.float64(0.1818524568524517), np.float64(0.032902411674092275), np.float64(0.043684622150646106), np.float64(0.03416152016234466), np.float64(0.1557961638121222), np.float64(0.1944276860091965), np.float64(0.2337865105347111), np.float64(0.2525254751455133), np.float64(0.40275771979353114), np.float64(0.10838730076078794), np.float64(0.37438573530795477), np.float64(0.26444111951468524), np.float64(0.5795995449007063), np.float64(0.19491648430901182), np.float64(0.25249373029586486), np.float64(0.24437929495095723), np.float64(0.36518225867019327), np.float64(0.035468671638735384), np.float64(0.29303246679976774), np.float64(0.3603610034273999), np.float64(0.09530467677105037), np.float64(0.21210597945715645), np.float64(0.03062277177139644), np.float64(0.1262296573372154), np.float64(0.12297515497906102), np.float64(0.21495299563189033), np.float64(0.22946815455840697), np.float64(0.26

In [31]:
# Estimación de la valoración
rating_user_u_item_i=0
for user_v in [k_zip[i][1] for i in range (len(k_zip))]:
    rating_user_u_item_i += (Y[user_v,item_i] - Y[user_v,R[user_v,:]>0].mean())*user_sim[user_u,user_v]
rating_user_u_item_i = user_u_average + rating_user_u_item_i/k_sim_suma
print('Valoración estimada\n',rating_user_u_item_i)

Valoración estimada
 2.9357600057880013
